name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      #    - name: Start docker containers
      #      run: docker-compose up -d
      #      working-directory: docker

      - name: Test
        run: bun run test
#    - name: Run integration test
#      run: npm run test-integration
